# Generated by Django 5.2.5 on 2025-08-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_alter_task_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_alerted",
            field=models.BooleanField(
                default=False, verbose_name="Уведомление отправлено"
            ),
        ),
    ]
