# Generated by Django 5.2.5 on 2025-08-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_task_is_alerted"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_expired",
            field=models.BooleanField(default=False, verbose_name="Просрочена"),
        ),
    ]
