# Generated by Django 5.2.5 on 2025-08-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_task_is_expired"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="is_alerted",
        ),
        migrations.AddField(
            model_name="task",
            name="is_alerted_expired",
            field=models.BooleanField(
                default=False, verbose_name="Уведомление о просрочке отправлено"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="is_alerted_hour",
            field=models.BooleanField(
                default=False, verbose_name="Уведомление за 1 час отправлено"
            ),
        ),
    ]
