# Generated by Django 5.2.5 on 2025-08-20 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0005_remove_task_is_alerted_task_is_alerted_expired_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
        ),
    ]
