# Generated by Django 5.2.5 on 2025-08-21 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_task_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_alerted_hour',
        ),
    ]
